# Generated by Django 5.1.7 on 2025-03-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_orderitem_book_id_remove_orderitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UZCARD', 'UzCard'), ('HUMO', 'Humo'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('CASH', 'Наличные при получении')], max_length=20),
        ),
    ]
